development:
  delivery_method: :sendmail
#   smtp_settings:
#     :address: localhost
#     :port: 25
#     :authentication: plain
#     :user_name: user
#     :password: pass
production:
  delivery_method: :sendmail
#   smtp_settings:
#     :address: smtp.server.com
#     :port: 25
#     :authentication: plain
#     :user_name: user
#     :password: pass
